version: 1
policy:
  pullRequests: public
tasks:
  - provisionerId: aws-provisioner-v1
    workerType: github-worker
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: node
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo && git config
          advice.detachedHead false && git checkout {{event.head.sha}} && npm
          install . && npm test
    metadata:
      name: ''
      description: ''
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
