version: 1
tasks:
  $let:
    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    clone_url:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.git_url}
      else: ${event.repository.url}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
      
    action:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.action}
      else: ${tasks_for}

  in:
    $if: '${action} in ["github-release", "github-push", "reopened"]'
    then:
      - provisionerId: proj-taskcluster
        workerType: ci
        deadline: {$fromNow: '3 hours'}
        metadata:
          name: TaskNameUserInput
          description: TaskDescriptionUserInput
          owner: email@UserInput.com
          source: ${repository}
        payload:
          maxRunTime: 3600
          image: node
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${clone_url} repo && cd repo && git config
              advice.detachedHead false && git checkout {$head_rev} && npm
              install . && npm test

