version: 1
tasks:
  $let:
    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else: ${event.after}

    clone_url:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.git_url}}
      else: ${event.repository.url}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}

  in:
    $if: 'tasks_for in ["github-pull-request", "github-push"]'
    then:
      - provisionerId: proj-taskcluster
        workerType: ci
        created: {$fromNow: ''}
        deadline: {$fromNow: '3 hours'}
        metadata:
          name: TaskNameUserInput
          description: TaskDescriptionUserInput
          owner: email@UserInput.com
          source: ${repository}
        payload:
          maxRunTime: 3600
          image: node
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${clone_url} repo && cd repo && git config
              advice.detachedHead false && git checkout {$head_rev} && npm
              install . && npm test

